### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by shubhamdev8** [TheByKotik/sbpp_discord#1]
its not working at all
no error logs

**Comment by TheByKotik** [comment]
Sorry for long response.
Did you installed last [SteamWorks Extension](http://users.alliedmods.net/~kyles/builds/SteamWorks/) ([Source Code](https://github.com/KyleSanderson/SteamWorks))?
Did you tested webhook url and connecting with `sm_discord_test "Hook type"` command?
Did you used precompiled plugin or compile it youself?

**Comment by shubhamdev8** [comment]
Yes i have steamworks installed
No i have not tested the webhook url with the command
I used your precompiled plugin

Reports are working and are showing in discord but bans, mutes, gags and silences are not working

**Comment by TheByKotik** [comment]
> Yes i have steamworks installed
> No i have not tested the webhook url with the command
> I used your precompiled plugin
> 
> Reports are working and are showing in discord but bans, mutes, gags and silences are not working

If you using different webhooks for reports and other, please test it with command above.
else if you use one hook, check redirect like:
```
	"Hooks"	// Discord webhook or name of another key to redirect. Disabled if empty.
	{
		"Reports"	"{hook1}"
		"Bans"		"{hook2}"
		"Silences"	"Bans"
		"Mutes"		"Bans"
		"Gags"		"Bans"
	}
```

**Comment by shubhamdev8** [comment]
Ohh yes im using single webhook for all

**Comment by TheByKotik** [comment]
> Ohh yes im using single webhook for all

Using like 1 or 2 method?
1:
```
{
	"Reports"	"{hook1}"
	"Bans"		"{hook1}"
	"Silences"	"{hook1}"
	"Mutes"		"{hook1}"
	"Gags"		"{hook1}"
}
```
2:
```
{
	"Reports"	"{hook1}"
	"Bans"		"Reports"
	"Silences"	"Reports"
	"Mutes"		"Reports"
	"Gags"		"Reports"
}
```

**Comment by shubhamdev8** [comment]
1

**Comment by TheByKotik** [comment]
> 1

You using last sbpp plugins?
Which is version SM?
What happing after use `sm_discord_test bans` command? No error logs and no message in discord?

**Comment by TheByKotik** [comment]
I'm still can't reproduce this issue.
I'm receive error on logs or message of successful sending.
Can you add me in discord? I need to see it myself.

**Comment by shubhamdev8** [comment]
sourcebans is latest
sm version
SourceMod 1.10.0.6456, by AlliedModders LLC

**Comment by shubhamdev8** [comment]
test commands are working
then why its not showing when ban or mute someone
u can add me FLASHING#8548
