### ISSUE TITLE
Change folder and file name

### ISSUE THREAD

**Issue by crashzk** [TheByKotik/sbpp_discord#3]
https://github.com/TheByKotik/sbpp_discord/blob/babe8b9fdb0a578b404fa3558eb7e173a382002c/sourcemod/scripting/sbpp_discord.sp#L277

Why not leave the SourceBans++ folder with `sourcebans` with the same name, so it reads in the same place that SourceBans reads and avoids having multiple enough for the same plugin so to speak. Would this change be possible in future updates?

I think it would be a good idea to change the file name from `discord.cfg` to` sb_discord.cfg`.

Would be like this:

> BuildPath( Path_SM, szBuf, sizeof szBuf, "configs/sourcebans/sb_discord.cfg" ); 

I believe that this makes something more beautiful, aesthetically. If you have no problem I can do a PR with these small changes.

**Comment by crashzk** [comment]
I took the liberty of creating this PR already, testing on my servers everything works fine.

#4

**Comment by TheByKotik** [comment]
> https://github.com/TheByKotik/sbpp_discord/blob/babe8b9fdb0a578b404fa3558eb7e173a382002c/sourcemod/scripting/sbpp_discord.sp#L277
> 
> Why not leave the SourceBans++ folder with `sourcebans` with the same name, so it reads in the same place that SourceBans reads and avoids having multiple enough for the same plugin so to speak. Would this change be possible in future updates?
> 
> I think it would be a good idea to change the file name from `discord.cfg` to` sb_discord.cfg`.
> 
> Would be like this:
> 
> > BuildPath( Path_SM, szBuf, sizeof szBuf, "configs/sourcebans/sb_discord.cfg" );
> 
> I believe that this makes something more beautiful, aesthetically. If you have no problem I can do a PR with these small changes.

Sorry for long response.
I'm avoid using `sourcebans` naming because **SourceBans++** and **vanilla SourceBans** very different projects and any conflicts is possible.
And IMHO not need double naming of files. It already in sourcebans directory!

**Comment by crashzk** [comment]
I understand, in any case, thank you.
