### ISSUE TITLE
[Feature Request} Sourcebans Web URL in Embed

### ISSUE THREAD

**Issue by shaikhnedab** [TheByKotik/sbpp_discord#8]
What about adding Sourcebans Web panel URL in the Embed like this?
[Link](https://github.com/Sarrus1/discord-forward/blob/2c576c80c392609340ee3e432571350f22d30f94/sbpp_discord.sp#L57)

It directly takes the user to Web Panel ``Ban Submissions`` Page

May be you can add configurable input for each embeds which links to respective page on Web Panel.

**Comment by crashzk** [comment]
https://github.com/sbpp/discord-forward/pull/14

It would be interesting

**Comment by TheByKotik** [comment]
Implemented in [1.7.0-50](https://github.com/TheByKotik/sbpp_discord/releases/tag/1.7.0-50).
(If i understand you correctly)

**Comment by crashzk** [comment]
Version is working but I believe that is not it.
```
  44 "SourceBans++ Discord" (1.7.0-50) by Kotik. Fork of RumbleFrog, SourceBans++ Dev Team.
```

![image](https://user-images.githubusercontent.com/32937653/128432145-437d6abe-a26e-4703-ab4f-261b9c1ee6cc.png)

![image](https://user-images.githubusercontent.com/32937653/128432193-ef0bee9b-d547-45bb-8aac-cca109d62f8e.png)

It would have to have a link to the sourcebans web interface, something like:
![image](https://user-images.githubusercontent.com/32937653/128432258-333e9f4a-c2ef-4568-980b-23bb67520745.png)

**Comment by TheByKotik** [comment]
Discord requires specify protocol to make links clickable.
 
![image](https://user-images.githubusercontent.com/40791562/128443196-a0b65587-9a6d-4459-93d1-8077b68fc462.png)

**Comment by crashzk** [comment]
Fixed it, added the protocol and still nothing.

![image](https://user-images.githubusercontent.com/32937653/128552516-d5abacf5-309b-4e34-adbf-83bea28ea07a.png)

![image](https://user-images.githubusercontent.com/32937653/128552549-1a620f4b-bfb9-4464-9171-1ed9a280bc61.png)

**Comment by TheByKotik** [comment]
> Fixed it, added the protocol and still nothing.

Have you reload the plugin?

**Comment by crashzk** [comment]
Yes, I restarted the server and even changed the map after the changes.

Accessing discord by cell phone is even more buggy, see print.

![128586883-db05b180-487b-49c7-8079-6bbc98814aab](https://user-images.githubusercontent.com/32937653/128602563-0db53336-7bd0-48b4-a788-e78145278d2b.png)

In any case I'll double check and restart the servers just to make sure.

**Comment by TheByKotik** [comment]
It's works for me, looks pretty strange.
![image](https://user-images.githubusercontent.com/40791562/128587024-c4cfe49b-cf26-49de-93b6-57814a215102.png)
![image](https://user-images.githubusercontent.com/40791562/128587042-32546a08-ff44-41ae-b5a8-f02dd7dc942d.png)

**Comment by TheByKotik** [comment]
> Accessing discord by cell phone is even more buggy, see print.

Now i see.
Make sure config file was saved correctly, it's look like file wasn't be saved after edit.
Because old value used.
Then:
`sm plugins reload sbpp_discord`

**Comment by crashzk** [comment]
all right now thanks. :smile:

![image](https://user-images.githubusercontent.com/32937653/128603395-e1614dc6-3263-40bc-bb94-495c0abcdbfb.png)

**Comment by crashzk** [comment]
Just to finish and you can close the issues.
```
"Timezone shift"  	""		// Server timezone shift in seconds.
```
This cvar would be configured by default on which? I would like to configure it for my region, but I didn't quite understand how it works and such.

**Comment by TheByKotik** [comment]
> Just to finish and you can close the issues.
> 
> ```
> "Timezone shift"  	""		// Server timezone shift in seconds.
> ```
> 
> This cvar would be configured by default on which? I would like to configure it for my region, but I didn't quite understand how it works and such.

This is just time shift for server time. 
You just must get server time zone (ex: +5 utc) and transform it to seconds (multiply for 60 and 60 again `5 * 60 * 60 = 18000` ).
Discord required this for correcting timestamps.
![1](https://user-images.githubusercontent.com/40791562/128605611-a4ba6839-bfb5-4887-ab60-15d876838f05.png)

**Comment by crashzk** [comment]
I believe this issues can be closed. It has already been implemented.
