### ISSUE TITLE
Error extension System2 v3.3.2 | Required GLIBCXX

### ISSUE THREAD

**Issue by crashzk** [TheByKotik/sbpp_discord#9]
I'm getting the following error:
```
sbpp_discord.smx (SourceBans++ Discord): Required extension "System2" file("system2.ext") not running
```

When I check the server extensions I have this error on **System2**:
```
[14] <FAILED> file "system2.ext.so": /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/ogp_agent/OGP_User_Files/whmcs/957/csgo/addons/sourcemod/extensions/system2.ext.so)
```
Would you have to update **GLIBCXX** to the version that is mentioned?

Strange is that this error started this month, before all plugins were working without errors, same thing the extensions.

The version of System2 I am using would be the most recent: https://github.com/dordnung/System2/releases/tag/v3.3.2

**Comment by TheByKotik** [comment]
If i understand you correctly, you just need to update your OS or system libraries.
